# Generated by Django 2.2.3 on 2019-07-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='external_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
