# Generated by Django 2.2.3 on 2019-07-16 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
